### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by mshiner** [south-west-communities/website#42]
Be nice to get a list of events as an RSS feed

**Comment by tonyedwardspz** [comment]
Hmm. Good idea.

How should we manage the amount of data? Should the RSS feed include all events, n amount or the next n days worth?

**Comment by mshiner** [comment]
Not totally sure on RSS but usually they have all the entries as they are just summaries/headers and the feed reader sorts it out.

Martyn Shiner
Consultant, uzERP LLP

**Comment by tonyedwardspz** [comment]
I've looked into this and will add a feed at some point soon.

For my future reference - https://methodmatters.github.io/rss-add-github-blog-to-r-bloggers/

**Comment by tonyedwardspz** [comment]
Forgot to ask... what feed reader do you use @mshiner? I'll be sure to test it in the same one.

**Comment by mshiner** [comment]
I've used Feedly in the past (when greader died) but now I use an Idieweb reader called Together - 
https://indieweb.org/Together

The hosted version is here https://alltogethernow.io/ and the Github repo is here https://github.com/alltogethernow/web

**Comment by tonyedwardspz** [comment]
Hey @mshiner 

I've added an RSS feed to the site. You can find it at https://southwestcommunities.co.uk/feed.xml .

Dropped the feed into Feedly and it seems to work fine..... but I don't really use RSS/Atom so not sure if the results are as expected. If you get a minute, can you check it's as you'd expect and let me know if there are issues?

For now, I'll close this issue but am happy to reopen if needed.

**Comment by mshiner** [comment]
Hi Tony

Have given it a go- Aperture recognises the feed OK and counts 115 entries - so all good I think

Martyn
